#!/usr/bin/env python3
"""Convert the Hello Kitty GIF into pink, colored ASCII animation frames.

Reads tools/hello-kitty.gif and writes kitty-frames.js at the repo root:

    window.KITTY_FRAMES = [ "<row html>\\n<row html>...", ... ];
    window.KITTY_FRAME_MS = 120;

Each frame is an HTML string of rows. Runs of same-color glyphs are wrapped in
a single <span style="color:#rrggbb"> to keep the DOM light; transparent pixels
become plain spaces outside any span. Brightness picks the glyph from a ramp,
and brightness + saturation pick a pink palette shade, so the result reads as
the original pink kitty.

Re-run after changing the source GIF:  python3 tools/gen-ascii.py
"""

import colorsys
import html
import json
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "hello-kitty.gif")
OUT = os.path.join(ROOT, "kitty-frames.js")

# Output grid. Kitty art is square; monospace cells are ~2:1 tall, so the
# height is roughly half the width to keep the picture from squashing.
GRID_W = 92
CHAR_ASPECT = 0.5
ALPHA_CUTOFF = 50  # below this the pixel is treated as transparent
FRAME_MS = 220  # slower, gentle dance

# Dark -> light glyph ramp.
RAMP = " .,:;irsXA253hMHGS#9B&@"

# Warm ivory monochrome, dark -> light. Reads as a glowing off-white figure on
# a near-black background — editorial, not cute.
PALETTE = [
    "#5b574e",  # dim (outlines)
    "#787163",
    "#968d7c",
    "#b4ab98",
    "#cfc6b2",
    "#e6ddc9",
    "#f4ecd9",  # brightest (fur highlights)
]


def pick_glyph(lum: float) -> str:
    # lum 0..1 ; darker pixels get the denser glyphs at the start of the ramp.
    idx = int(round((1.0 - lum) * (len(RAMP) - 1)))
    return RAMP[max(0, min(len(RAMP) - 1, idx))]


def pick_color(r: int, g: int, b: int) -> str:
    _h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    # Map brightness onto the pink ramp; brighter pixel -> lighter palette entry.
    idx = int(round(l * (len(PALETTE) - 1)))
    # Very desaturated + bright pixels are the white fur; keep them near-white.
    if s < 0.12 and l > 0.6:
        idx = max(idx, len(PALETTE) - 2)
    return PALETTE[max(0, min(len(PALETTE) - 1, idx))]


def frame_cells(rgba: Image.Image):
    """Return a grid_h x GRID_W grid of cells: (glyph, color) or None (transparent)."""
    grid_h = max(1, int(round(GRID_W * CHAR_ASPECT * rgba.height / rgba.width)))
    small = rgba.resize((GRID_W, grid_h), Image.BILINEAR)
    px = small.load()

    grid = []
    for y in range(grid_h):
        row = []
        for x in range(GRID_W):
            r, g, b, a = px[x, y]
            if a < ALPHA_CUTOFF:
                row.append(None)
            else:
                lum = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
                row.append((pick_glyph(lum), pick_color(r, g, b)))
        grid.append(row)
    return grid


def emit_row(cells) -> str:
    """Render a row of cells to HTML. Same-color runs share one span; transparent
    cells become literal spaces. Width is preserved (no trailing trim) so every
    frame keeps identical dimensions."""
    parts = []
    buf = []
    cur = None  # current color, None => plain spaces

    def flush():
        if not buf:
            return
        text = html.escape("".join(buf))
        parts.append(text if cur is None else f'<span style="color:{cur}">{text}</span>')

    for cell in cells:
        color, glyph = (None, " ") if cell is None else (cell[1], cell[0])
        if color != cur:
            flush()
            buf.clear()
            cur = color
        buf.append(glyph)
    flush()
    return "".join(parts)


def main() -> None:
    im = Image.open(SRC)
    n = getattr(im, "n_frames", 1)

    grids = []
    for i in range(n):
        im.seek(i)
        grids.append(frame_cells(im.convert("RGBA")))

    # Shared bounding box across ALL frames, so the figure never resizes or
    # shifts between frames — it stays one fixed size and only "dances".
    top, bottom, left, right = len(grids[0]), -1, GRID_W, -1
    for grid in grids:
        for y, row in enumerate(grid):
            for x, cell in enumerate(row):
                if cell is not None:
                    top = min(top, y)
                    bottom = max(bottom, y)
                    left = min(left, x)
                    right = max(right, x)

    frames = []
    for grid in grids:
        rows = [emit_row(grid[y][left : right + 1]) for y in range(top, bottom + 1)]
        frames.append("\n".join(rows))

    payload = (
        "// Auto-generated by tools/gen-ascii.py from tools/hello-kitty.gif.\n"
        "// Do not edit by hand; re-run the script to regenerate.\n"
        "window.KITTY_FRAMES = "
        + json.dumps(frames, ensure_ascii=False)
        + ";\n"
        + f"window.KITTY_FRAME_MS = {FRAME_MS};\n"
    )
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(payload)
    print(f"Wrote {OUT}: {len(frames)} frames, {len(payload)} bytes")


if __name__ == "__main__":
    main()
