#!/usr/bin/env python3
"""Convert the Hello Kitty GIF into pink, colored ASCII animation frames.

Reads tools/hello-kitty.gif and writes kitty-frames.js at the repo root:

    window.KITTY_FRAMES = [ "<row html>\\n<row html>...", ... ];
    window.KITTY_FRAME_MS = 120;

Each frame is an HTML string of rows. Runs of same-color glyphs are wrapped in
a single <span style="color:#rrggbb"> to keep the DOM light; transparent pixels
become plain spaces outside any span. Brightness picks the glyph from a ramp,
and brightness + saturation pick a pink palette shade, so the result reads as
the original pink kitty.

Re-run after changing the source GIF:  python3 tools/gen-ascii.py
"""

import colorsys
import html
import json
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "hello-kitty.gif")
OUT = os.path.join(ROOT, "kitty-frames.js")

# Output grid. Kitty art is square; monospace cells are ~2:1 tall, so the
# height is roughly half the width to keep the picture from squashing.
GRID_W = 92
CHAR_ASPECT = 0.5
ALPHA_CUTOFF = 50  # below this the pixel is treated as transparent
FRAME_MS = 120

# Dark -> light glyph ramp.
RAMP = " .,:;irsXA253hMHGS#9B&@"

# Warm ivory monochrome, dark -> light. Reads as a glowing off-white figure on
# a near-black background — editorial, not cute.
PALETTE = [
    "#5b574e",  # dim (outlines)
    "#787163",
    "#968d7c",
    "#b4ab98",
    "#cfc6b2",
    "#e6ddc9",
    "#f4ecd9",  # brightest (fur highlights)
]


def pick_glyph(lum: float) -> str:
    # lum 0..1 ; darker pixels get the denser glyphs at the start of the ramp.
    idx = int(round((1.0 - lum) * (len(RAMP) - 1)))
    return RAMP[max(0, min(len(RAMP) - 1, idx))]


def pick_color(r: int, g: int, b: int) -> str:
    _h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    # Map brightness onto the pink ramp; brighter pixel -> lighter palette entry.
    idx = int(round(l * (len(PALETTE) - 1)))
    # Very desaturated + bright pixels are the white fur; keep them near-white.
    if s < 0.12 and l > 0.6:
        idx = max(idx, len(PALETTE) - 2)
    return PALETTE[max(0, min(len(PALETTE) - 1, idx))]


def build_frame(rgba: Image.Image) -> str:
    grid_h = max(1, int(round(GRID_W * CHAR_ASPECT * rgba.height / rgba.width)))
    small = rgba.resize((GRID_W, grid_h), Image.BILINEAR)
    px = small.load()

    rows = []
    for y in range(grid_h):
        parts = []
        buf = []          # current run of characters
        cur_color = None  # None => plain (transparent spaces)

        def flush():
            if not buf:
                return
            text = html.escape("".join(buf))
            if cur_color is None:
                parts.append(text)
            else:
                parts.append(f'<span style="color:{cur_color}">{text}</span>')

        for x in range(GRID_W):
            r, g, b, a = px[x, y]
            if a < ALPHA_CUTOFF:
                target_color, glyph = None, " "
            else:
                lum = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
                target_color, glyph = pick_color(r, g, b), pick_glyph(lum)
            if target_color != cur_color:
                flush()
                buf = []
                cur_color = target_color
            buf.append(glyph)
        flush()
        rows.append("".join(parts).rstrip())

    # Trim fully-empty leading/trailing rows for tighter framing.
    while rows and rows[0] == "":
        rows.pop(0)
    while rows and rows[-1] == "":
        rows.pop()
    return "\n".join(rows)


def main() -> None:
    im = Image.open(SRC)
    n = getattr(im, "n_frames", 1)
    frames = []
    for i in range(n):
        im.seek(i)
        frames.append(build_frame(im.convert("RGBA")))

    payload = (
        "// Auto-generated by tools/gen-ascii.py from tools/hello-kitty.gif.\n"
        "// Do not edit by hand; re-run the script to regenerate.\n"
        "window.KITTY_FRAMES = "
        + json.dumps(frames, ensure_ascii=False)
        + ";\n"
        + f"window.KITTY_FRAME_MS = {FRAME_MS};\n"
    )
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(payload)
    print(f"Wrote {OUT}: {len(frames)} frames, {len(payload)} bytes")


if __name__ == "__main__":
    main()
